#!/usr/bin/env bash

# Check if less than 4 arguments were passed
if [ "$#" -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Save arguments to variables
FILE=$1
IP=$2
USER=$3
SSH_KEY=$4

# Use scp to send the file
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USER@$IP:~/"
