#!/usr/bin/env bash
# Transfers a file to the home directory of a remote server using SCP

# Check for correct number of arguments
if [ "$#" -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to named variables
FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Transfer the file using scp with strict host checking disabled
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$IP:~/"
